stages:
    - test

variables:
    IMAGE=registry.gitlab.com/quorrax/docker/runner/node

.test:
    before_script:
        - npm install
        - npm update
    script:
        - npm test
    stage: test

Node.js LTS:
    extends:
        - .test
    image: ${IMAGE}:lts

Node.js Current:
    extends:
        - .test
    image: ${IMAGE}:current
