cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - public/

stages:
    - build
    - test

variables:
    IMAGE: registry.gitlab.com/quorrax/docker/runner/node

.build:
    script:
        - npm run build-css
        - npm run build-js
    stage: build

.test:
    before_script:
        - npm install
        - npm update
    script:
        - npm test
    stage: test

Node.js 10 Build:
    extends:
        - .build
    image: ${IMAGE}:10

Node.js 12 Build:
    extends:
        - .build
    image: ${IMAGE}:12

Node.js 14 Build:
    extends:
        - .build
    image: ${IMAGE}:14

Node.js 15 Build:
    extends:
        - .build
    image: ${IMAGE}:15

Node.js Current Build:
    extends:
        - .build
    image: ${IMAGE}:current

Node.js LTS Build:
    extends:
        - .build
    image: ${IMAGE}:lts

Node.js 10 Test:
    extends:
        - .test
    image: ${IMAGE}:10

Node.js 12 Test:
    extends:
        - .test
    image: ${IMAGE}:12

Node.js 14 Test:
    extends:
        - .test
    image: ${IMAGE}:14

Node.js 15 Test:
    extends:
        - .test
    image: ${IMAGE}:15

Node.js Current Test:
    extends:
        - .test
    image: ${IMAGE}:current

Node.js LTS Test:
    extends:
        - .test
    image: ${IMAGE}:lts
